name: NodeJS with Webpack

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Build
        run: |
          echo $GITHUB_TOKEN
